[build]
  functions = "src/functions"  # Make sure this matches your actual functions directory
  publish = "public"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"  # Ensure you're using the correct Node.js version
